version: '3.5'

services:
  rov-web-bru-prod:
    build: .
    image: rov-web-bru:prod
    container_name: rov-web-bru-prod
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rov-web-bru-node
    ports:
      - 8091:8091
    command: npm run start
networks:
  rov-web-bru-node:
    name: rov-web-bru-node-prod
    driver: bridge
